Section "Device"
    Identifier "ST7789"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
    Option "ShadowFB" "off"
EndSection

Section "Screen"
    Identifier "LCD"
    Device "ST7789"
    DefaultDepth 16
    SubSection "Display"
        Depth 16
        Modes "320x170"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "ZeroDay"
    Screen "LCD"
EndSection